#!/usr/bin/env python

import sys
from ase.io.castep import read_geom
from ase.io.castep import write_cell

seed = sys.argv[1].split('.geom')[0]

atoms = read_geom(seed + '.geom')[-1]
write_cell(seed + '_opt.cell', atoms)

