#!/usr/bin/env python

import sys
import os
import re
infofile = sys.argv[1]

tick  = None
jobfolder = None 

pattern = r'(tick[\d]+).*'

with open(infofile, 'r') as f:
    for l in f:
        match_obj = re.match(pattern, l)
        if match_obj:
            tick = match_obj.groups()[0]
        if l.startswith('+ mkdir -p /scratch/'):
            jobfolder = l.split()[-1]

print('/net/%s%s'%(tick,jobfolder))
