# This file is part of rtools.
#
#    rtools is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    rtools is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with rtools.  If not, see <http://www.gnu.org/licenses/>.

"""
rtools is great!

The following documentation of the rtools module is autogenerated from the
docstrings of the modules.

---
Simon P. Rittmeyer (simon.rittmeyer(at)tum.de)
Christph Schober (christoph.schober(at)ch.tum.de)
"""

__version__ = '0.2.1'

## this is just legacy....
## screw those damn legacy imports...
#from rtools.misc import get_close_matches
#from rtools.misc import get_cmd_args
#from rtools.misc import format_timing

#from rtools.filesys import mkdir
#from rtools.filesys import gzip_file

#from rtools.helpers import castephelpers

## only import if we have matplotlib installed...
#try:
#    from rtools.helpers import matplotlibhelpers
#except ImportError:
#    pass

## only import if we have pandas installed...
#try:
#    from rtools.helpers import pandashelpers
#except ImportError:
#    pass
